### ISSUE TITLE
Properly cite sources

### ISSUE THREAD

**Issue by rushilsrivastava** [cvrve/New-Grad#15]
### Issue/Question

Glad y'all like the Simplify team's repositories :)

The least you could do is credit the original authors who put a lot of love in shipping out a free community resource. The entire repo has been lifted without a single mention of the original author. @matttreed put a lot of effort to make this all come to life

**Comment by vanshb03** [comment]
Hey Rushil, 

Apologize for the oversight, Citing the Simplify team's branding in the next commit :)

**Comment by vanshb03** [comment]
Cited in fbc6795. 

Appreciate your understanding and the valuable work the Simplify team has done. <3
