### ISSUE TITLE
Fixing ServiceNow UTG Link

### ISSUE THREAD

**Issue by Ashishjob** [cvrve/New-Grad#328]
### Link to Job Posting

https://careers.servicenow.com/en/jobs/744000011870000/utg-software-engineer-new-college-grad/

### Company Name

ServiceNow

### Job Title

New Grad 2025: UTG - Software Engineer

### Location

Santa Clara, CA

### Does this job offer sponsorship?

Other

### Is this job posting currently accepting applications?

Yes

### Permanently remove this job from the list?

- [ ] Yes, remove this job

### Email associated with your GitHub account (Optional)

ashishjob104@gmail.com

### Reason for edit

The original link doesn’t work

**Comment by vanshb03** [comment]
Odd that it isn't allowing the form to edit, will check actions logs and will amend it 😁
