### ISSUE TITLE
Editing Role

### ISSUE THREAD

**Issue by pranavsenthil5** [cvrve/New-Grad#384]
### Link to Job Posting

https://www.capitalonecareers.com/job/mclean/technology-development-program-associate-february-2025/31238/69740859456

### Does this job offer sponsorship?

Does Not Offer Sponsorship

### Is this job posting currently accepting applications?

None

### Permanently remove this job from the list?

- [ ] Yes, remove this job

**Comment by ajain02** [comment]
why?
