### ISSUE TITLE
Misc Issue - Explicit New Grad Postings vs. Speculative New Grad Postings

### ISSUE THREAD

**Issue by RizzwareEngineer** [cvrve/New-Grad#404]
### Issue/Question

Distinguish between JDs that **explicitly** mention New Grad, Early Talent, Early Career, etc. and general Software Engineer JDs that are **speculated** to be for New Grad...

There are already a handful of postings that are clearly for engineers one level or so above the New Grad level.   

Just make a separate channel in the resumes.fyi Discord. Something like `maybe-new-grad-postings`.

**Comment by bhanumeka1** [comment]
Hey, I am new to this.
I know this is out of context but can I please get the discord invite for resumes.fyi

**Comment by vanshb03** [comment]
> ### Issue/Question
> Distinguish between JDs that **explicitly** mention New Grad, Early Talent, Early Career, etc. and general Software Engineer JDs that are **speculated** to be for New Grad...
> 
> There are already a handful of postings that are clearly for engineers one level or so above the New Grad level.
> 
> Just make a separate channel in the resumes.fyi Discord. Something like `maybe-new-grad-postings`.

Hey @RizzwareEngineer ,

Should the `maybe-new-grad-postings` channel include job descriptions that don't explicitly mention those terms but are speculated to be suitable for new grads? If so, what criteria would you use for speculation (e.g., required experience level, job title, etc.)?

Definitely able to make that change following an idea of criteria :)

**Comment by vanshb03** [comment]
> Hey, I am new to this. I know this is out of context but can I please get the discord invite for resumes.fyi

@bhanumeka1 

https://discord.gg/Q8Kd3Cv9U8
