### ISSUE TITLE
Bloomberg New Grad SWE

### ISSUE THREAD

**Issue by quantumscholar** [cvrve/New-Grad#542]
### Link to Job Posting

 https://bloomberg.avature.net/careers/JobDetail/2025-Software-Engineer-New-York/6961

### Company Name

Bloomberg

### Job Title

Software Engineer (New Grad)

### Location

New York, NY

### Does this job offer sponsorship?

Offers Sponsorship

### Is this internship currently accepting applications?

Yes

**Comment by vanshb03** [comment]
Hey @quantumscholar ,

The role was posted on the repo about 10 days ago. Thanks for your contribution!
